input {
  # Logstash écoute les logs envoyés par Airflow via le port 8081
  http {
    port => 8081
    codec => json
    # Si tu veux sécuriser l'entrée Logstash elle-même :
    # user => "admin"
    # password => "admin"
  }
}

filter {
  # Airflow envoie parfois les composants du log_id séparément.
  # On les fusionne ici pour que l'ID corresponde à ce qu'Airflow cherchera à lire.
  if [dag_id] {
    mutate {
      add_field => { 
        "log_id" => "%{dag_id}-%{task_id}-%{run_id}-%{try_number}" 
      }
    }
  }

  # Nettoyage des métadonnées HTTP pour ne garder que les logs dans Elasticsearch
  mutate {
    remove_field => ["headers", "@version", "host"]
  }
}

output {
  # Envoi des logs vers Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "airflow-logs-%{+YYYY.MM.dd}"
    
    # AUTHENTIFICATION VERS ELASTICSEARCH
    user => "admin"
    password => "admin"

    # IMPORTANT : On définit l'ID du document comme étant le log_id.
    # C'est ce qui permet à Airflow de retrouver le log exact instantanément.
    document_id => "%{log_id}"
  }

  # Debug : Affiche les logs reçus dans le terminal (docker logs -f logstash)
  stdout { 
    codec => rubydebug 
  }
}